name: 'GitHub checks updater'
description: 'Marks all previously executed check runs for a given commit ref as successful'
inputs:
  github_token:
    description: 'GitHub token'
    required: true
  check_name:
    description: 'Check run name'
    required: true
  ref:
    description: 'git ref to update'
    required: false
    default: ''
runs:
  using: "composite"
  steps:
    - name: Print deprecation message
      run: |
        echo "⚠️ This GitHub Action is deprecated and no longer runs any checks."
        echo "Input check_name: ${{ inputs.check_name }}"
        echo "Input ref: ${{ inputs.ref }}"
      shell: bash
